#test_minimal.tavern.yaml
test_name: Get some fake data from the JSON placeholder

strict:
  - json:off

stages:
  - name: Make sure we have the right ID
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      json:
        id: 1
      save:
        json:
          returned_id: id